server:
  port: 3344

spring:
  application:
    name:  config-server #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/laughboyjyh/Springcloud.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - springcloud
      ####读取分支
      label: main


#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
